-- V1: Migration inicial para criação do schema do banco de dados
-- Criação das tabelas tb_cadastro e tb_missoes com suas colunas e restrições básicas
-- Define PKs, UNIQUE para email e FK de tb_cadastro para tb_missoes

CREATE TABLE tb_cadastro
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    email      VARCHAR(255),
    img_url    VARCHAR(255),
    idade      INT,
    missoes_id BIGINT,
    CONSTRAINT pk_tb_cadastro PRIMARY KEY (id)
);

CREATE TABLE tb_missoes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    dificuldade VARCHAR(255),
    CONSTRAINT pk_tb_missoes PRIMARY KEY (id)
);

ALTER TABLE tb_cadastro
    ADD CONSTRAINT uc_tb_cadastro_email UNIQUE (email);

ALTER TABLE tb_cadastro
    ADD CONSTRAINT FK_TB_CADASTRO_ON_MISSOES FOREIGN KEY (missoes_id) REFERENCES tb_missoes (id);